export const customers = [
    {
        Account_number: 10000,
        First_Name: "Vanessa",
        Last_Name: "Newman",
        Address: "907 Sanguine Pth.",
        Town: "Waiville",
        Province: "Ontario",
        Country: "Canada",
        Email: "vnewman@catdogburger.com",
        Phone: "(945) 308-0092",
        Package_id: 0,
        AP_id: 0,
    },
    {
        Account_number: 10001,
        First_Name: "Edward",
        Last_Name: "Dyer",
        Address: "650 Trepidation Ave.",
        Town: "Moose Liambriri",
        Province: "Ontario",
        Country: "Canada",
        Email: "edyer@bigdogpizza.com",
        Phone: "(937) 639-9014",
        Package_id: 0,
        AP_id: 5,
    },
    {
        Account_number: 10002,
        First_Name: "Victoria",
        Last_Name: "MacLeod",
        Address: "280 Golden Alley",
        Town: "Ranskel",
        Province: "Ontario",
        Country: "Canada",
        Email: "vmacleod@lostmytoothdentist.com",
        Phone: "(566) 514-0028",
        Package_id: 1,
        AP_id: 8,
    },
    {
        Account_number: 10003,
        First_Name: "Connor",
        Last_Name: "Knox",
        Address: "691 Jade Way",
        Town: "San Laie",
        Province: "Ontario",
        Country: "Canada",
        Email: "cknox@haveanitchytoe.com",
        Phone: "(431) 480-8885",
        Package_id: 3,
        AP_id: 0,
    },
    {
        Account_number: 10004,
        First_Name: "Piers",
        Last_Name: "Peake",
        Address: "770 Basilisk Pthw.",
        Town: "Fort Unhurst",
        Province: "Ontario",
        Country: "Canada",
        Email: "ppeake@treesgonewild.com",
        Phone: "(649) 530-7829",
        Package_id: 4,
        AP_id: 4,
    },
    {
        Account_number: 10005,
        First_Name: "Christian",
        Last_Name: "Johnston",
        Address: "722 Riverside Pass",
        Town: "Great Pencham",
        Province: "Ontario",
        Country: "Canada",
        Email: "cjohnston@goskydivingonmars.com",
        Phone: "(783) 638-0301",
        Package_id: 5,
        AP_id: 1,
    },
    {
        Account_number: 10006,
        First_Name: "Julian",
        Last_Name: "Oliver",
        Address: "149 Corling Route",
        Town: "Grand Ngateslac",
        Province: "Ontario",
        Country: "Canada",
        Email: "joliver@haveaschnitzel.com",
        Phone: "(223) 666-4938",
        Package_id: 4,
        AP_id: 2,
    },
    {
        Account_number: 10007,
        First_Name: "Lauren",
        Last_Name: "McGrath",
        Address: "510 Rochtona Way",
        Town: "Mootreecha",
        Province: "Ontario",
        Country: "Canada",
        Email: "lmcgrath@extracheeselasagna.com",
        Phone: "(938) 972-7996",
        Package_id: 4,
        AP_id: 6,
    },
    {
        Account_number: 10008,
        First_Name: "Joanne",
        Last_Name: "McDonald",
        Address: "657 Wakegonie Ave.",
        Town: "Miside",
        Province: "Ontario",
        Country: "Canada",
        Email: "jmcdonald@spicyicecream.com",
        Phone: "(225) 950-8376",
        Package_id: 3,
        AP_id: 8,
    },
    {
        Account_number: 10009,
        First_Name: "Neil",
        Last_Name: "Taylor",
        Address: "208 Islingdover Pass",
        Town: "Thorpe",
        Province: "Ontario",
        Country: "Canada",
        Email: "ntaylor@tacobelisnotmexican.com",
        Phone: "(327) 954-9695",
        Package_id: 2,
        AP_id: 5,
    },
    {
        Account_number: 10010,
        First_Name: "Lillian",
        Last_Name: "Nash",
        Address: "849 Invisible Way",
        Town: "Sandgasp Upon Alncho",
        Province: "Ontario",
        Country: "Canada",
        Email: "lnash@dontrobbanks.com",
        Phone: "(920) 402-1439",
        Package_id: 5,
        AP_id: 0,
    },
    {
        Account_number: 10011,
        First_Name: "Jasmine",
        Last_Name: "Cornish",
        Address: "745 Flowing Ave.",
        Town: "Bridombrna",
        Province: "Ontario",
        Country: "Canada",
        Email: "jcornish@whereiswaldo.com",
        Phone: "(831) 570-3463",
        Package_id: 0,
        AP_id: 5,
    },
    {
        Account_number: 10012,
        First_Name: "Samantha",
        Last_Name: "Mackay",
        Address: "85 Hungry Ave.",
        Town: "Ninggrayl",
        Province: "Ontario",
        Country: "Canada",
        Email: "smackay@beyondmeatisgross.com",
        Phone: "(593) 369-2451",
        Package_id: 1,
        AP_id: 8,
    },
    {
        Account_number: 10013,
        First_Name: "Owen",
        Last_Name: "Butler",
        Address: "106 Everlasting Passage",
        Town: "West Georgencou",
        Province: "Ontario",
        Country: "Canada",
        Email: "obutler@gohunting.com",
        Phone: "(446) 509-3050",
        Package_id: 4,
        AP_id: 0,
    },
    {
        Account_number: 10014,
        First_Name: "John",
        Last_Name: "Parsons",
        Address: "720 Lightning Hwy.",
        Town: "Burtrois",
        Province: "Ontario",
        Country: "Canada",
        Email: "jparsons@wherearemykeys.com",
        Phone: "(979) 663-6308",
        Package_id: 2,
        AP_id: 8,
    },
    {
        Account_number: 10015,
        First_Name: "Pippa",
        Last_Name: "Newman",
        Address: "107 Fallen Star Way",
        Town: "Vicclun Heath",
        Province: "Ontario",
        Country: "Canada",
        Email: "pnewman@whoatemysandwich.com",
        Phone: "(431) 540-9702",
        Package_id: 3,
        AP_id: 9,
    },
    {
        Account_number: 10016,
        First_Name: "Nicola",
        Last_Name: "Butler",
        Address: "284 Gladborough St.",
        Town: "Derstur",
        Province: "Ontario",
        Country: "Canada",
        Email: "nbutler@cleanyourroom.com",
        Phone: "(930) 900-7094",
        Package_id: 1,
        AP_id: 9,
    },
    {
        Account_number: 10017,
        First_Name: "Jack",
        Last_Name: "Turner",
        Address: "91 Barringgus Trail",
        Town: "La Em",
        Province: "Ontario",
        Country: "Canada",
        Email: "jturner@haveaniceday.com",
        Phone: "(724) 876-1533",
        Package_id: 4,
        AP_id: 5,
    },
    {
        Account_number: 10018,
        First_Name: "Vanessa",
        Last_Name: "Ogden",
        Address: "181 Wallcola Pthw.",
        Town: "South Coketyne",
        Province: "Ontario",
        Country: "Canada",
        Email: "vogden@rainbowsandbutterflies.com",
        Phone: "(481) 436-3069",
        Package_id: 1,
        AP_id: 4,
    },
    {
        Account_number: 10019,
        First_Name: "Carol",
        Last_Name: "Harris",
        Address: "334 Kirdale Route",
        Town: "East Wesbru",
        Province: "Ontario",
        Country: "Canada",
        Email: "charris@butterfries.com",
        Phone: "(237) 404-7587",
        Package_id: 4,
        AP_id: 0,
    },
    {
        Account_number: 10020,
        First_Name: "Yvonne",
        Last_Name: "Peters",
        Address: "578 Restless Hwy.",
        Town: "Raywed Valley",
        Province: "Ontario",
        Country: "Canada",
        Email: "ypeters@arewethereyet.com",
        Phone: "(979) 566-7960",
        Package_id: 1,
        AP_id: 6,
    },
    {
        Account_number: 10021,
        First_Name: "Christian",
        Last_Name: "Thomson",
        Address: "134 Emerald St.",
        Town: "Naceodeal",
        Province: "Ontario",
        Country: "Canada",
        Email: "cthomson@programmersarethebest.com",
        Phone: "(888) 806-6347",
        Package_id: 2,
        AP_id: 6,
    },
    {
        Account_number: 10022,
        First_Name: "Carol",
        Last_Name: "Manning",
        Address: "579 Crystal Way",
        Town: "Port Gonsainte Under Francesshil",
        Province: "Ontario",
        Country: "Canada",
        Email: "cmanning@buildanapp.com",
        Phone: "(879) 951-0306",
        Package_id: 3,
        AP_id: 1,
    },
    {
        Account_number: 10023,
        First_Name: "Leonard",
        Last_Name: "White",
        Address: "307 Butcher Pthw.",
        Town: "Wleyhar Beach",
        Province: "Ontario",
        Country: "Canada",
        Email: "lwhite@alwaysrecycle.com",
        Phone: "(796) 749-6694",
        Package_id: 1,
        AP_id: 2,
    },
    {
        Account_number: 10024,
        First_Name: "Edward",
        Last_Name: "Vaughan",
        Address: "663 Five Mile Hwy.",
        Town: "Moose Har",
        Province: "Ontario",
        Country: "Canada",
        Email: "evaughan@gotoshcool.com",
        Phone: "(435) 272-8988",
        Package_id: 2,
        AP_id: 3,
    },
    {
        Account_number: 10025,
        First_Name: "Ella",
        Last_Name: "MacDonald",
        Address: "752 Scorpion Pass",
        Town: "Mensmore",
        Province: "Ontario",
        Country: "Canada",
        Email: "emacdonald@dontbemean.com",
        Phone: "(904) 275-5872",
        Package_id: 2,
        AP_id: 2,
    },
    {
        Account_number: 10026,
        First_Name: "Mary",
        Last_Name: "Dickens",
        Address: "985 Emdiac Ave.",
        Town: "Rseatirket Bay",
        Province: "Ontario",
        Country: "Canada",
        Email: "mdickens@laughoutloud.com",
        Phone: "(700) 621-8433",
        Package_id: 3,
        AP_id: 5,
    },
    {
        Account_number: 10027,
        First_Name: "Keith",
        Last_Name: "Allan",
        Address: "498 Wellingsend Track",
        Town: "Red Stonrnard",
        Province: "Ontario",
        Country: "Canada",
        Email: "kallan@whatistofu.com",
        Phone: "(727) 958-0663",
        Package_id: 4,
        AP_id: 5,
    },
    {
        Account_number: 10028,
        First_Name: "Irene",
        Last_Name: "Rees",
        Address: "262 Wesheim Rd.",
        Town: "Port Crookjunc-In-Fleetgee",
        Province: "Ontario",
        Country: "Canada",
        Email: "irees@coronavirussucks.com",
        Phone: "(870) 318-2065",
        Package_id: 1,
        AP_id: 2,
    },
    {
        Account_number: 10029,
        First_Name: "Isaac",
        Last_Name: "White",
        Address: "115 Wellingtown Passage",
        Town: "Thirsknagerahampton",
        Province: "Ontario",
        Country: "Canada",
        Email: "iwhite@startabusiness.com",
        Phone: "(384) 844-1817",
        Package_id: 2,
        AP_id: 2,
    },
    {
        Account_number: 10030,
        First_Name: "Stephen",
        Last_Name: "Miller",
        Address: "871 Falcon Claw Pth.",
        Town: "New Portdge",
        Province: "Ontario",
        Country: "Canada",
        Email: "smiller@beagamer.com",
        Phone: "(213) 925-8333",
        Package_id: 3,
        AP_id: 1,
    },
    {
        Account_number: 10031,
        First_Name: "Charles",
        Last_Name: "Jackson",
        Address: "559 Adamantine Ave.",
        Town: "Grand Palm",
        Province: "Ontario",
        Country: "Canada",
        Email: "cjackson@ysoserius.com",
        Phone: "(915) 900-0571",
        Package_id: 1,
        AP_id: 1,
    },
    {
        Account_number: 10032,
        First_Name: "Nathan",
        Last_Name: "Ogden",
        Address: "796 Frozen Mountain Alley",
        Town: "Great Chisnod Du Wiste",
        Province: "Ontario",
        Country: "Canada",
        Email: "nogden@eattacosforbreakfast.com",
        Phone: "(510) 375-2644",
        Package_id: 0,
        AP_id: 4,
    },
    {
        Account_number: 10033,
        First_Name: "Katherine",
        Last_Name: "Robertson",
        Address: "284 Deserted Way",
        Town: "West Derno",
        Province: "Ontario",
        Country: "Canada",
        Email: "krobertson@dontworrybehappy.com",
        Phone: "(306) 302-3278",
        Package_id: 1,
        AP_id: 4,
    },
    {
        Account_number: 10034,
        First_Name: "Justin",
        Last_Name: "Skinner",
        Address: "815 Volcano Trail",
        Town: "West Holt",
        Province: "Ontario",
        Country: "Canada",
        Email: "jskinner@workfromhome.com",
        Phone: "(382) 770-4149",
        Package_id: 4,
        AP_id: 7,
    },
    {
        Account_number: 10035,
        First_Name: "Adrian",
        Last_Name: "Mitchell",
        Address: "995 Quiet Pass",
        Town: "Bridforbarrers",
        Province: "Ontario",
        Country: "Canada",
        Email: "amitchell@2buckteethforabuck.com",
        Phone: "(780) 598-4683",
        Package_id: 2,
        AP_id: 7,
    },
    {
        Account_number: 10036,
        First_Name: "Peter",
        Last_Name: "Watson",
        Address: "131 Gibtane Ave.",
        Town: "Quoiscor",
        Province: "Ontario",
        Country: "Canada",
        Email: "pwatson@robertoppenheimer.com",
        Phone: "(709) 698-3282",
        Package_id: 3,
        AP_id: 7,
    },
    {
        Account_number: 10037,
        First_Name: "Dan",
        Last_Name: "Dowd",
        Address: "752 Niater Pthw.",
        Town: "Uthighville",
        Province: "Ontario",
        Country: "Canada",
        Email: "ddowd@sheldoncooper.com",
        Phone: "(374) 894-1707",
        Package_id: 0,
        AP_id: 8,
    },
    {
        Account_number: 10038,
        First_Name: "Stephanie",
        Last_Name: "Welch",
        Address: "388 Bracefolk Pass",
        Town: "Saint Kingclehae",
        Province: "Ontario",
        Country: "Canada",
        Email: "swelch@nacholibre.com",
        Phone: "(856) 672-3434",
        Package_id: 2,
        AP_id: 5,
    },
    {
        Account_number: 10039,
        First_Name: "Joshua",
        Last_Name: "Randall",
        Address: "902 Attlecour Walk",
        Town: "Viltotnes-On-River",
        Province: "Ontario",
        Country: "Canada",
        Email: "jrandall@jalapenoandcheesenachos.com",
        Phone: "(883) 935-5888",
        Package_id: 1,
        AP_id: 3,
    },
    {
        Account_number: 10040,
        First_Name: "Lily",
        Last_Name: "McLean",
        Address: "5 Fiery Trail",
        Town: "West Rellny",
        Province: "Ontario",
        Country: "Canada",
        Email: "lmclean@drinkcoffeeallday.com",
        Phone: "(334) 568-5902",
        Package_id: 4,
        AP_id: 6,
    },
    {
        Account_number: 10041,
        First_Name: "Austin",
        Last_Name: "Ferguson",
        Address: "867 Riverside Pthw.",
        Town: "Fort Vilhav Under Boysgrove",
        Province: "Ontario",
        Country: "Canada",
        Email: "aferguson@technoisnotdubstep.com",
        Phone: "(826) 946-3296",
        Package_id: 1,
        AP_id: 9,
    },
    {
        Account_number: 10042,
        First_Name: "Brandon",
        Last_Name: "Metcalfe",
        Address: "509 Phoenix Trail",
        Town: "Mi",
        Province: "Ontario",
        Country: "Canada",
        Email: "bmetcalfe@iworkonlinux.com",
        Phone: "(771) 736-4607",
        Package_id: 3,
        AP_id: 5,
    },
    {
        Account_number: 10043,
        First_Name: "Lauren",
        Last_Name: "Ellison",
        Address: "915 Black Forest St.",
        Town: "Mount Leycon",
        Province: "Ontario",
        Country: "Canada",
        Email: "lellison@grammashomecoooking.com",
        Phone: "(371) 789-8103",
        Package_id: 2,
        AP_id: 4,
    },
    {
        Account_number: 10044,
        First_Name: "Molly",
        Last_Name: "Thomson",
        Address: "89 Arid Rd.",
        Town: "Bourhill",
        Province: "Ontario",
        Country: "Canada",
        Email: "mthomson@goforadrive.com",
        Phone: "(555) 675-6378",
        Package_id: 4,
        AP_id: 2,
    },
    {
        Account_number: 10045,
        First_Name: "Claire",
        Last_Name: "Nash",
        Address: "53 Burning Fire Pass",
        Town: "Broughchway",
        Province: "Ontario",
        Country: "Canada",
        Email: "cnash@lavakillstrees.com",
        Phone: "(635) 239-2524",
        Package_id: 1,
        AP_id: 3,
    },
    {
        Account_number: 10046,
        First_Name: "Michelle",
        Last_Name: "Welch",
        Address: "504 Flatstable Hwy.",
        Town: "Great Tuckstain",
        Province: "Ontario",
        Country: "Canada",
        Email: "mwelch@whotookmypen.com",
        Phone: "(200) 458-8137",
        Package_id: 0,
        AP_id: 6,
    },
    {
        Account_number: 10047,
        First_Name: "Ava",
        Last_Name: "Hill",
        Address: "404 Leswell Walk",
        Town: "Great Whitefritow",
        Province: "Ontario",
        Country: "Canada",
        Email: "ahill@stopthemadnes.com",
        Phone: "(333) 808-6012",
        Package_id: 2,
        AP_id: 0,
    },
    {
        Account_number: 10048,
        First_Name: "Kimberly",
        Last_Name: "Young",
        Address: "544 Plygan Way",
        Town: "Red Turoopag",
        Province: "Ontario",
        Country: "Canada",
        Email: "kyoung@ifoundmytextbook.com",
        Phone: "(685) 896-4246",
        Package_id: 3,
        AP_id: 0,
    },
    {
        Account_number: 10049,
        First_Name: "Evan",
        Last_Name: "Gill",
        Address: "769 Bellegue Hwy.",
        Town: "Alrold",
        Province: "Ontario",
        Country: "Canada",
        Email: "egill@wholetthedogsout.com",
        Phone: "(968) 934-0606",
        Package_id: 2,
        AP_id: 0,
    },
];

export const packages = [
    {
        ID: 0,
        Name: "Unlimited 10",
        Data_Limit: "Unlimited",
        Upload_speed: 5,
        Download_speed: 10,
    },
    {
        ID: 1,
        Name: "Unlimited 20",
        Data_Limit: "Unlimited",
        Upload_speed: 10,
        Download_speed: 20,
    },
    {
        ID: 2,
        Name: "Unlimited 30",
        Data_Limit: "Unlimited",
        Upload_speed: 15,
        Download_speed: 30,
    },
    {
        ID: 3,
        Name: "Unlimited 40",
        Data_Limit: "Unlimited",
        Upload_speed: 20,
        Download_speed: 40,
    },
    {
        ID: 4,
        Name: "Unlimited 50",
        Data_Limit: "Unlimited",
        Upload_speed: 25,
        Download_speed: 50,
    },
];

export const access_points = [
    {
        ID: 0,
        Name: "AP 1",
        Latitude: 42.284407,
        Longitude: -82.973549,
        Radius: 5,
        Status: "up",
    },
    {
        ID: 1,
        Name: "AP 2",
        Latitude: 42.124728,
        Longitude: -82.990361,
        Radius: 4,
        Status: "up",
    },
    {
        ID: 2,
        Name: "AP 3",
        Latitude: 42.264163,
        Longitude: -82.709094,
        Radius: 10,
        Status: "down",
    },
    {
        ID: 3,
        Name: "AP 4",
        Latitude: 42.186232,
        Longitude: -82.400458,
        Radius: 21,
        Status: "up",
    },
    {
        ID: 4,
        Name: "AP 5",
        Latitude: 42.279905,
        Longitude: -82.218325,
        Radius: 2,
        Status: "up",
    },
    {
        ID: 5,
        Name: "AP 6",
        Latitude: 42.407972,
        Longitude: -82.335988,
        Radius: 7,
        Status: "down",
    },
    {
        ID: 6,
        Name: "AP 7",
        Latitude: 42.05573,
        Longitude: -82.555961,
        Radius: 30,
        Status: "up",
    },
    {
        ID: 7,
        Name: "AP 8",
        Latitude: 42.298651,
        Longitude: -82.418053,
        Radius: 6,
        Status: "up",
    },
    {
        ID: 8,
        Name: "AP 9",
        Latitude: 42.278436,
        Longitude: -81.999897,
        Radius: 5,
        Status: "down",
    },
    {
        ID: 9,
        Name: "AP 10",
        Latitude: 42.507319,
        Longitude: -81.800469,
        Radius: 28,
        Status: "up",
    },
];
